services:
  postgres:
    image: postgres:16-alpine
    container_name: beat-the-crew-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beat-the-crew
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  beat-the-crew-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: beat-the-crew-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/beat-the-crew
      NODE_ENV: development

      # optional if hot reload acts stupid
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "
      pnpm prisma generate &&
      pnpm prisma migrate deploy &&
      pnpm start:dev
      "

volumes:
  postgres_data: